<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <!-- POM file generated with GWT webAppCreator -->
  <modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>fi.parentgwt</groupId>
		<artifactId>parentgwt</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<relativePath>../ParentGWT</relativePath>
	</parent>
  <groupId>nl.numworx.fsm</groupId>
  <artifactId>fsmgwt</artifactId>
  <packaging>war</packaging>
  <name>nl.numworx.fsmgwt.Fsmgwt</name>

  <properties>

    <!-- Setting maven.compiler.source to something different to 1.8
         needs that you configure the sourceLevel in gwt-maven-plugin since
         GWT compiler 2.8 and above requires 1.8 (see gwt-maven-plugin block below) -->
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>

    <!-- Don't let your Mac use a crazy non-standard encoding -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <euclidesVersion>${authorVersion}</euclidesVersion>
    <gwtVersion>2.8.2</gwtVersion>

  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- ensure all GWT deps use the same version (unless overridden) -->
      <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt</artifactId>
        <version>${gwtVersion}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-servlet</artifactId>
      <scope>runtime</scope>
      <version>${gwtVersion}</version>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <scope>provided</scope>
      <version>${gwtVersion}</version>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <scope>provided</scope>
      <version>${gwtVersion}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
    	<groupId>nl.numworx.fsm</groupId>
    	<artifactId>fsm</artifactId>
    	<version>${authorVersion}</version>
    </dependency>
    <dependency>
    	<groupId>nl.numworx.fsm</groupId>
    	<artifactId>fsm</artifactId>
    	<version>${authorVersion}</version>
    	<classifier>sources</classifier>
    </dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<classifier>sources</classifier>
		</dependency>

		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-gwt</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${euclidesVersion}</version>
			<classifier>sources</classifier>
		</dependency>
  </dependencies>

  <build>
    <!-- Output classes directly into the webapp, so that IDEs and "mvn process-classes" update them in DevMode -->
    <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>

    <plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<localWorkers>1</localWorkers>
					<module>nl.numworx.fsmgwt.Fsmgwt</module>
					<runTarget>Fsmgwt.html</runTarget>
					<warSourceDirectory>${basedir}/src/main/webapp</warSourceDirectory>
					<extraJvmArgs>-Xms768m -Xmx1024m</extraJvmArgs>
					<hostedWebapp>${webappDirectory}</hostedWebapp>
					<port>8888</port>
				</configuration>
				<executions>
					<execution>
						<id>compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

<!--       GWT Maven Plugin-->
<!--      <plugin>-->
<!--        <groupId>net.ltgt.gwt.maven</groupId>-->
<!--        <artifactId>gwt-maven-plugin</artifactId>-->
<!--        <version>1.0.1</version>-->
<!--        <executions>-->
<!--          <execution>-->
<!--            <goals>-->
<!--              <goal>compile</goal>-->
<!--              <goal>test</goal>-->
<!--            </goals>-->
<!--          </execution>-->
<!--        </executions>-->
<!--        <configuration>-->
<!--          <moduleName>nl.numworx.fsmgwt.Fsmgwt</moduleName>-->
<!--          <moduleShortName>Fsmgwt</moduleShortName>-->
<!--          <failOnError>true</failOnError>-->
<!--           GWT compiler 2.8 and above requires 1.8, hence define sourceLevel here if you use-->
<!--               a different source language for java compilation -->
<!--          <sourceLevel>1.8</sourceLevel>-->
<!--           Compiler configuration -->
<!--          <compilerArgs>-->
<!--             Ask GWT to create the Story of Your Compile (SOYC) (gwt:compile) -->
<!--            <arg>-compileReport</arg>-->
<!--            <arg>-XcompilerMetrics</arg>-->
<!--          </compilerArgs>-->
<!--           DevMode configuration -->
<!--          <warDir>${project.build.directory}/${project.build.finalName}</warDir>-->
<!--          <classpathScope>compile+runtime</classpathScope>-->
<!--           URL(s) that should be opened by DevMode (gwt:devmode). -->
<!--          <startupUrls>-->
<!--            <startupUrl>Fsmgwt.html</startupUrl>-->
<!--          </startupUrls>-->
<!--        </configuration>-->
<!--      </plugin>-->

      <!-- Skip normal test execution, we use gwt:test instead -->
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.17</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>

    </plugins>
  </build>
</project>
