<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>fi.parentgwt</groupId>
		<artifactId>ParentGWT</artifactId>
		<version>0.0.3</version>
	</parent>
	<groupId>nl.numworx.geodefinergwt</groupId>
	<artifactId>GeoDefinerGWT</artifactId>
	<version>0.0.2-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>GeoDefiner GWT</name>
	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}</version><!--$NO-MVN-MAN-VER$-->
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-gwt</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${euclidesVersion}</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geodefiner</groupId>
			<artifactId>geodefiner-common</artifactId>
			<version>0.0.2-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>formule</artifactId>
			<version>${formuleVersion}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.mgwt</groupId>
			<artifactId>MGWT</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.ideas</groupId>
			<artifactId>IdeasGWT</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.vectomatic</groupId>
			<artifactId>lib-gwt-svg</artifactId>
			<version>0.5.11</version>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdrgwt</groupId>
			<artifactId>WiskOpdrGWT</artifactId>
			<version>0.0.4-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>${project.artifactId}</finalName>
		<outputDirectory>target/${project.build.finalName}/WEB-INF/classes</outputDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<warSourceDirectory>war</warSourceDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<module>${project.groupId}.${project.artifactId}${debug}</module>
					<runTarget>${project.artifactId}${debug}.html</runTarget>
					<warSourceDirectory>war</warSourceDirectory>
					<extraJvmArgs>-Xms768m -Xmx1024m</extraJvmArgs>
					<hostedWebapp>${webappDirectory}</hostedWebapp>
					<i18nConstantsWithLookupBundles>
						<i18nConstantsWithLookupBundle>nl.numworx.geodefinergwt.client.i18n.messages</i18nConstantsWithLookupBundle>
					</i18nConstantsWithLookupBundles>
				</configuration>
				<executions>
					<execution>
						<id>compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
					<execution>
						<id>i18n</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>i18n</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.8</version>
				<executions>
					<execution>
						<id>unpack</id>
						<goals>
							<goal>unpack</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>fi.euclides</groupId>
									<artifactId>euclides-resources</artifactId>
									<version>${euclidesVersion}</version>
									<type>jar</type>
									<overWrite>true</overWrite>
									<outputDirectory>${project.build.directory}/${project.artifactId}/geodefinergwt${debug}/</outputDirectory>
									<includes>**/*.png,**/*.gif,**/*.jpg</includes>
								</artifactItem>
							</artifactItems>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>							
						</configuration>
					</execution>
				</executions>
			</plugin>


		</plugins>
	</build>
	<properties>
		<euclidesVersion>0.0.3-SNAPSHOT</euclidesVersion>
		<formuleVersion>0.0.5</formuleVersion>
		<debug />
		<gwtVersion>2.7.0</gwtVersion>
		<gwt.style>OBFUSCATED</gwt.style> <!--  -D gwt.style=PRETTY -->
		<gwt.compiler.force>true</gwt.compiler.force>	
	</properties>
	<scm>
		<developerConnection>scm:svn:https://svn.science.uu.nl/repos/sci.velth101.numworx/GeoDefinerGWT/trunk</developerConnection>
	</scm>
</project>
