<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.graphtoolgwt</groupId>
  <artifactId>GraphToolGWT</artifactId>
  <packaging>war</packaging>
  <name>Grafieken tool</name>
  <build>
  	<finalName>${project.artifactId}</finalName>
	<sourceDirectory>src</sourceDirectory>
  	<testSourceDirectory>test</testSourceDirectory>
    <resources>
    	<resource>
    	   <directory>src</directory>
    	</resource>
    </resources>
  	<plugins>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
        	<warSourceDirectory>war</warSourceDirectory>
        	<attachClasses>true</attachClasses>
        	<packagingIncludes>*.css,*gwt/**,${project.artifactId}.html</packagingIncludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwtVersion}</version>
         <configuration>
              <module>${project.groupId}.${project.artifactId}</module>
              <runTarget>${project.artifactId}.html</runTarget>
        	  <warSourceDirectory>war</warSourceDirectory>        
             </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
             </goals>
          </execution>
          </executions>
      </plugin>
      <plugin>
<!-- usage: jetty:run-war of jetty:run-exploded -->
  		<groupId>org.eclipse.jetty</groupId>
 		<artifactId>jetty-maven-plugin</artifactId>
  			<version>9.0.0.v20130308</version>
  	  </plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>interaction</artifactId>
  	</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.ideas</groupId>
			<artifactId>IdeasGWT</artifactId>
			<version>0.0.2</version>
		</dependency>
  	<dependency>
  		<groupId>fi.wiskopdrgwt</groupId>
  		<artifactId>WiskOpdrGWT</artifactId>
  		<version>0.0.2</version>
  		<exclusions>
  			<exclusion>
  				<artifactId>IdeasGWT</artifactId>
  				<groupId>nl.uu.fi.dwo.ideas</groupId>
  			</exclusion>
  		</exclusions>
  	</dependency>
  	<dependency>
  		<groupId>com.googlecode.mgwt</groupId>
  		<artifactId>MGWT</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>gwt.geom</groupId>
  		<artifactId>gwt-geom</artifactId>
  		<version>0.0.1</version>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>formule</artifactId>
  		<version>0.0.4</version>
  	</dependency>
  	<dependency>
  		<groupId>fi.beans</groupId>
  		<artifactId>lineairealgebra</artifactId>
  		<version>0.0.1</version>
  	</dependency>
  		<dependency>
		<groupId>fi.beans</groupId>
		<artifactId>lineairealgebra</artifactId>
		<version>0.0.1</version>
		<classifier>sources</classifier>			
	</dependency>  	
  </dependencies>
  <parent>
  	<groupId>fi.parentgwt</groupId>
  	<artifactId>ParentGWT</artifactId>
  	<version>0.0.3</version>
  	<relativePath>../ParentGWT</relativePath>
  </parent>
  <version>2.1.20</version>
</project>
