<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.parentgwt</groupId>
    <artifactId>ParentGWT</artifactId>
    <version>0.0.2</version>
  </parent>
  <groupId>nl.numworx.geodefinergwt</groupId>
  <artifactId>GeoDefinerGWT</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>GeoDefiner GWT</name>
  <dependencies>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>interaction</artifactId>
  	</dependency>
    <dependency>
    	<groupId>fi.euclides</groupId>
    	<artifactId>euclides-gwt</artifactId>
    	<version>${euclidesVersion}</version>
    </dependency>
    <dependency>
    	<groupId>fi.euclides</groupId>
    	<artifactId>euclides-expr</artifactId>
    	<version>${euclidesVersion}</version>
    </dependency>
    <dependency>
    	<groupId>fi.euclides</groupId>
    	<artifactId>euclides-expr</artifactId>
    	<version>${euclidesVersion}</version>
    	<classifier>sources</classifier>
    </dependency>
  	<dependency>
  		<groupId>nl.numworx.geodefiner</groupId>
  		<artifactId>geodefiner-common</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>formule</artifactId>
  		<version>${formuleVersion}</version>
  	</dependency>
  	<dependency>
  		<groupId>com.googlecode.mgwt</groupId>
  		<artifactId>MGWT</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.ideas</groupId>
  		<artifactId>IdeasGWT</artifactId>
  		<version>0.0.1</version>
  	</dependency>
  </dependencies>
  <build>
  	<outputDirectory>target/${project.artifactId}-${project.version}/WEB-INF/classes</outputDirectory>
  	<plugins>
              <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <warSourceDirectory>war</warSourceDirectory>
                </configuration>
            </plugin>
  	            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwtVersion}</version>
                <configuration>
                    <module>${project.groupId}.${project.artifactId}</module>
                    <runTarget>${project.artifactId}.html</runTarget>
                    <warSourceDirectory>war</warSourceDirectory>
                    <extraJvmArgs>-Xms768m -Xmx1024m</extraJvmArgs>
                    <hostedWebapp>${webappDirectory}</hostedWebapp>
<!--                     <i18nConstantsWithLookupBundles> -->
<!--                         <i18nConstantsWithLookupBundle>fi.euclides.client.expr.symbols</i18nConstantsWithLookupBundle>                           -->
<!--                     </i18nConstantsWithLookupBundles> -->
<!-- generate in generated sources, why not? -->
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
  	
  	
  	</plugins>
  </build>
  <properties>
  	<euclidesVersion>0.0.1-SNAPSHOT</euclidesVersion>
  	<formuleVersion>0.0.2</formuleVersion>
  </properties>
</project>
