<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.parentgwt</groupId>
  <artifactId>ParentGWT</artifactId>
  <version>0.0.7-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>parent pom for GWT widgets</name>
  <modules>
	<module>../WiskOpdrPlayer</module>
	<module>../WidgetPlayer</module>
  	<module>../AlgebraExprGWT</module>
  	<module>../AlgebraPijlenGWT</module>
  	<module>../BalansFruitGWT</module>
	<module>../BinomVerdGWT</module>
	<module>../CalculatorGWT</module>
	<module>../DoorzienGWT</module>
	<module>../DraaibankGWT</module>
	<module>../GeomAlgGWT</module>
	<module>../Grafiek3DGWT</module>
	<module>../GraphToolGWT</module>
	<module>../HeksGWT</module>
	<module>../KansbomenGWT</module>
	<module>../KladjeGWT</module>
	<module>../LeerdoelWidgetGWT</module>
	<module>../MozarchGWT</module>
	<module>../NabouwenAanzichtenGWT</module>
	<module>../NormVerdGWT</module>
	<module>../Repl</module>
	<module>../SliderWidgetGWT</module>
	<module>../StatistiekGWT</module>
	<module>../StatSimGWT</module>
	<module>../TegelsLeggenGWT</module>
	<module>../TekenVeelvlakGWT</module>
	<module>../VerknippenGWT</module>
	<module>../WebLogoGWT</module>
	<module>../WebLogo3dGWT</module>
	<module>../GeoDefinerGWT</module>
	<module>../StippelPatronenGWT</module>
	<module>../StroomDiagrammenGWT</module>
  </modules>
  <properties>
  	<gwtVersion>2.8.2</gwtVersion>
  	<mgwtVersion>1.1.2</mgwtVersion>
  	<maven.compiler.source>1.8</maven.compiler.source>
  	<maven.compiler.target>1.8</maven.compiler.target>
  	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  	<interactionVersion>0.0.5</interactionVersion>
  </properties>
  <dependencyManagement>
   <dependencies>
  	<dependency>
  		<groupId>com.googlecode.mgwt</groupId>
  		<artifactId>MGWT</artifactId>
  		<version>${mgwtVersion}</version>
  	</dependency>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
  		<version>${gwtVersion}</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>interaction</artifactId>
  		<version>${interactionVersion}</version>
  	</dependency>
   </dependencies>
  </dependencyManagement>
  <build>
  	<pluginManagement>
  		<plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-toolchains-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
      <execution>
        <goals>
          <goal>toolchain</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <toolchains>
        <jdk>
          <version>1.8</version>
        </jdk>
      </toolchains>
    </configuration>
  </plugin>
  <plugin>
        	<artifactId>maven-war-plugin</artifactId>
        	<version>3.2.3</version>
    		<configuration>
       			<warSourceDirectory>war</warSourceDirectory>
       			<warSourceExcludes>*gwt/</warSourceExcludes>
        		<packagingIncludes>*.css,*gwt/**,${project.artifactId}.html</packagingIncludes>
        	</configuration>
   	      </plugin>
    	  <plugin>
    		<artifactId>maven-compiler-plugin</artifactId>
    		<version>3.6.1</version>   	
    	  </plugin>
   		</plugins>
  	</pluginManagement> 
  </build>
    <parent>
    	<groupId>nl.uu.fi.dwo</groupId>
    	<artifactId>DWO.master.pom</artifactId>
    	<version>1.1</version>
    </parent>
</project>
