<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <parent>
    	<groupId>fi.parentgwt</groupId>
    	<artifactId>widgets-parent</artifactId>
    	<version>1.0.0-SNAPSHOT</version>
    </parent>
  <groupId>fi.parentgwt</groupId>
  <artifactId>ParentGWT</artifactId>
  <version>0.0.9-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>parent pom for GWT widgets</name>
  <properties>
  	<gwtVersion>2.8.2</gwtVersion>
  	<mgwtVersion>2.0.0</mgwtVersion>
  	<maven.compiler.source>1.8</maven.compiler.source>
  	<maven.compiler.target>1.8</maven.compiler.target>
	<maven.javadoc.skip>true</maven.javadoc.skip>
  	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  	<interactionVersion>2.5.47</interactionVersion>
  </properties>
  <modules>
	<module>../WiskOpdrPlayer</module>
	<module>../WidgetPlayer</module>
	<module>../PrintPlayer</module>
	<module>../AIModelGWT</module>
  	<module>../AlgebraExprGWT</module>
  	<module>../AlgebraPijlenGWT</module>
  	<module>../BalansFruitGWT</module>
	<module>../BinomVerdGWT</module>
	<module>../CalculatorGWT</module>
	<module>../DoorzienGWT</module>
	<module>../DraaibankGWT</module>
	<module>../GeomAlgGWT</module>
	<module>../Grafiek3DGWT</module>
	<module>../GraphToolGWT</module>
	<module>../HeksGWT</module>
	<module>../KansbomenGWT</module>
	<module>../KladjeGWT</module>
	<module>../LeerdoelWidgetGWT</module>
	<module>../MozarchGWT</module>
	<module>../NabouwenAanzichtenGWT</module>
	<module>../NormVerdGWT</module>
	<module>../ReplGWT</module>
	<module>../SliderWidgetGWT</module>
	<module>../StatistiekGWT</module>
	<module>../StatSimGWT</module>
	<module>../TegelsLeggenGWT</module>
	<module>../TekenVeelvlakGWT</module>
	<module>../VerknippenGWT</module>
	<module>../WebLogoGWT</module>
	<module>../WebLogo3dGWT</module>
	<module>../GeoDefinerGWT</module>
	<module>../StippelPatronenGWT</module>
	<module>../StroomDiagrammenGWT</module>
	<module>../SQLiteGWT</module>
  </modules>
  <dependencyManagement>
   <dependencies>
  	<dependency>
  		<groupId>com.googlecode.mgwt</groupId>
  		<artifactId>mgwt</artifactId>
  		<version>${mgwtVersion}</version>
  	</dependency>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
  		<version>${gwtVersion}</version>
  		<scope>provided</scope>
  	</dependency>
	<dependency>
		<groupId>org.gwtproject</groupId>
		<artifactId>gwt-user</artifactId>
  		<version>${gwtVersion}</version>
		<scope>provided</scope>
	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>interaction</artifactId>
  		<version>${interactionVersion}</version>
  	</dependency>
   </dependencies>
  </dependencyManagement>
 	<repositories>	<!-- als de mirror uit staat -->
                    <repository>
                     <id>numworx-dwo-openmath</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-openmath</url>
                  </repository>
                    <repository>
                     <id>numworx-dwo-project</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
                  </repository>
	</repositories>
  <build>
  	<plugins>
    		<plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<configuration>
                	<!-- see goals wiki page for configuration options -->
                	<flowInitContext>
             			<developBranchName>develop</developBranchName>  
             			<masterBranchName>main</masterBranchName>    	
                	</flowInitContext>
                	<localOnly>false</localOnly>
                	<allowSnapshots>false</allowSnapshots>
                	<enableSshAgent>true</enableSshAgent>
			<noDeploy>true</noDeploy>
            	</configuration>
        	</plugin>
  	</plugins>
  	<pluginManagement>
  		<plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-toolchains-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
      <execution>
        <goals>
          <goal>toolchain</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <toolchains>
        <jdk>
          <version>1.8</version>
        </jdk>
      </toolchains>
    </configuration>
  </plugin>
  <plugin>
        	<artifactId>maven-war-plugin</artifactId>
        	<version>3.2.3</version>
    		<configuration>
       			<warSourceDirectory>war</warSourceDirectory>
       			<warSourceExcludes>*gwt/</warSourceExcludes>
        		<packagingIncludes>*.css,*gwt/**</packagingIncludes>
        	</configuration>
   	      </plugin>
    	  <plugin>
    		<artifactId>maven-compiler-plugin</artifactId>
    		<version>3.6.1</version>   	
    	  </plugin>
    	  <plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<version>1.0-m5.1</version>
				  <dependencies>
				    <dependency>
				      <groupId>com.jcraft</groupId>
				      <artifactId>jsch</artifactId>
				      <version>0.1.54</version>
				    </dependency>
				  </dependencies>
    	  </plugin>
   		</plugins>
  	</pluginManagement> 
  </build>
    <scm>
        <developerConnection>scm:git:git@github.com:UtrechtUniversity/numworx-gwt-widgets.git</developerConnection>
    </scm>
</project>
