<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.uu.fi.dwo</groupId>
    <artifactId>DWO-GWT</artifactId>
    <version>1.1</version>
  </parent>
  <groupId>nl.uu.fi.dwo.mobile</groupId>
  <artifactId>WidgetPlayer</artifactId>
  <version>2.5.20-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>Widget Player</name>
  <properties>
	<finalName>WidgetPlayer</finalName>
	<gwtModule>${project.groupId}.WidgetPlayer</gwtModule>
	<gwt.style>OBFUSCATED</gwt.style>
	<runTarget>${project.artifactId}.html</runTarget>
  </properties>
  <dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<scope>provided</scope>
		</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>DWOplayer</artifactId>
  		<version>2.5.20-SNAPSHOT</version>
  		<classifier>classes</classifier>
  		<exclusions>
  			<exclusion>
  				<groupId>fi.wiskopdrgwt</groupId>
  				<artifactId>WiskOpdrGWT</artifactId>
  			</exclusion>
  		</exclusions>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>DWOplayer</artifactId>
  		<version>2.5.20-SNAPSHOT</version>
  		<classifier>sources</classifier>
  		<exclusions>
  			<exclusion>
  				<groupId>fi.wiskopdrgwt</groupId>
  				<artifactId>WiskOpdrGWT</artifactId>
  			</exclusion>
  		</exclusions>
  	</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<version>0.1.15</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<version>0.1.15</version>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
  </dependencies>
  <build>
	<finalName>${finalName}</finalName>
  	<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<module>${gwtModule}</module>
					<runTarget>${runTarget}</runTarget>
					<extraJvmArgs>-Xms768m -Xmx2048m</extraJvmArgs>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
  	</plugins>
  </build>
</project>
