<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>fi.parentgwt</groupId>
		<artifactId>parentgwt</artifactId>
		<relativePath>../ParentGWT</relativePath>
		<version>2.5.50</version>
	</parent>
	<groupId>fi.graphtoolgwt</groupId>
	<artifactId>graphtoolgwt</artifactId>
	<name>GraphToolGWT</name>
	<packaging>war</packaging>
	<description>Grafieken tool</description>
	<build>
		<finalName>${project.artifactId}</finalName>
		<sourceDirectory>src</sourceDirectory>
		<testSourceDirectory>test</testSourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<warSourceDirectory>war</warSourceDirectory>
					<attachClasses>true</attachClasses>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<module>${project.groupId}.${project.name}</module>
					<runTarget>${project.name}.html</runTarget>
					<warSourceDirectory>war</warSourceDirectory>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<!-- usage: jetty:run-war of jetty:run-exploded -->
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.0.0.v20130308</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<goals>deploy</goals>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
		</dependency>
		<dependency>
			<groupId>fi.statistiekgwt</groupId>
			<artifactId>statistiekgwt</artifactId>
			<version>${project.version}</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.ideas</groupId>
			<artifactId>IdeasGWT</artifactId>
			<version>0.1.9</version>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdrgwt</groupId>
			<artifactId>wiskopdrgwt</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>IdeasGWT</artifactId>
					<groupId>nl.uu.fi.dwo.ideas</groupId>
				</exclusion>
				<exclusion>
					<groupId>nl.uu.fi.dwo.mobile</groupId>
					<artifactId>interaction</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>gwt.geom</groupId>
			<artifactId>gwt-geom</artifactId>
			<version>${authorVersion}</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>formule</artifactId>
			<exclusions>
				<exclusion>
					<groupId>nl.uu.fi.dwo.mobile</groupId>
					<artifactId>interaction</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
		    <groupId>com.vaadin.addon</groupId>
		    <artifactId>pointer-events</artifactId>
		    <version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<properties>
		<gwt.style>PRETTY</gwt.style>
		<gwtVersion>2.9.0</gwtVersion>
	</properties>
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt</artifactId>
      <version>${gwtVersion}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
</project>
